apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: b19dccn248/loans:s23
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: LOANS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: AUTH_SERVICE_URL
        - name: AUTHORIZATION_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: AUTHORIZATION_SERVER_URL
        - name: TOKEN_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: TOKEN_SERVER_URL
---
apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
